name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'

jobs:
  go-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Download Go Modules
        working-directory: tests
        run: go mod download

      - name: Set ssh keys for github remote download
        working-directory: tests
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_GITHUB }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

#      - name: Run Go Tests
#        working-directory: tests
#        run: |
#          go test -v
#        env:
#          # TF ENVIRONMENT
#          TF_AZURE_STORAGE_ACCOUNT: "${{ secrets.NONPROD_AZURE_STORAGE_ACCOUNT }}"
#          TF_AZURE_CONTAINER: "${{ secrets.NONPROD_AZURE_STORAGE_CONTAINER  }}"
#          ARM_ACCESS_KEY: "${{ secrets.NONPROD_ARM_ACCESS_KEY }}"
